### PR TITLE
Trying to solve issue #249.

### PR DESCRIPTION
**Pull request by bmelo**
Only tested with a small sample.

### CODE REVIEW

**Comment by yarikoptic** [comment]
so it did resolve the #249 issue for you on your data?

**Comment by yarikoptic** [comment]
FWIW since tests did pass in #251 it means that sorting the filename at those points did cause some kind of change in behavior in our pipeline.

**Comment by bmelo** [comment]
Sorry, I did a very minimalist test and it passed. Now I saw the mistake and I'll fix this in a few minutes.

**Comment by yarikoptic** [comment]
according to the coverage report it seems to do change logic : https://codecov.io/gh/nipy/heudiconv/pull/250/src/heudiconv/convert.py  not sure yet if for the better.  So, to start with would be nice if you could test on your "full" case.  I will test on mine later on to see if that is somehow changes things unexpectedly

**Comment by bmelo** [comment]
Hi @yarikoptic , I tested with 4 different datasets (3 Siemens, 1 Philips) and using T1w, bold, and fmap sequences. Heudiconv converted everything without errors.
In one of these datasets, I need to export all fmap sequences (82 sessions) again, and the validator does not report any error. 

For now, I'm going to have to use this version because error #249 is recurring in our environment. Thank you!

**Comment by yarikoptic** [comment]
I thought we had merged this one awhile back... I was wrong.
Since we only heard confirmations that it resolved the issue, I will just merge this for now as is.

**Pull request merged**
