### PR TITLE
rebase, add basic test

### PR DESCRIPTION
**Pull request by bpinsard**

### CODE REVIEW

**Comment by yarikoptic** [comment]
something went wrong with rebase I guess...

**Comment by bpinsard** [comment]
Yes, tried to rebase, if I open the PR to master it shows commits correctly, but not when opening to enh-custom-seqinfo.
Maybe if nipy branch get rebased first it will fix the issue.

**Comment by yarikoptic** [comment]
I have rebased https://github.com/nipy/heudiconv/pull/581 now, invited you to join our heudiconv team so you could push directly into that PR (just never push to master please ;) )

**Comment by bpinsard** [comment]
Great, should we add a branch protection rule for master?

**Pull request closed without merging**
