### PR TITLE
sty: readme formatting, link to condensed slides

### PR DESCRIPTION
**Pull request by mgxd**
* currently hosting new tutorial slides on my fork, but would be great if we could host on `nipy.github.io/heudiconv`

### CODE REVIEW

**Comment by yarikoptic** [comment]
so why they are not yet hosted there? ;)

**Comment by mgxd** [comment]
you may need to change this in the repo settings? I pushed a branch [`nipy/heudiconv/gh-pages`](https://github.com/nipy/heudiconv/tree/gh-pages)

**Comment by yarikoptic** [comment]
oh -- are we having another pydicom migration issue?  I thought we mocked it all up... grrr

**Comment by yarikoptic** [comment]
re hosting: I guess there is a generic redirect for the entirety of the `nipy.github.io`:
```shell
$> wget https://nipy.github.io/heudiconv/
--2018-03-19 10:43:21--  https://nipy.github.io/heudiconv/
Resolving nipy.github.io (nipy.github.io)... 151.101.117.147, 2a04:4e42:1c::403
Connecting to nipy.github.io (nipy.github.io)|151.101.117.147|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://nipy.org/heudiconv/ [following]
--2018-03-19 10:43:21--  http://nipy.org/heudiconv/
Resolving nipy.org (nipy.org)... 192.30.252.154, 192.30.252.153
Connecting to nipy.org (nipy.org)|192.30.252.154|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-19 10:43:21 ERROR 404: Not Found.
```
I think we would be better of disabling gh-pages, and establishing proper `docs/` with e.g. sphinx to build the website --I now enabled it on readthedocs: http://heudiconv.readthedocs.io  but it blank obviously...  @satra - what do you think -- how should we organize documentation for the heudiconv?

**Comment by satra** [comment]
@yarikoptic - i have at least enabled the slides: `http://nipy.org/heudiconv/`

but yes in the longer term it would be good to have readthedocs and api and others. let's chat later today.

**Comment by mgxd** [comment]
closing in favor of 0808afff1e643196ef5069cbf41644c9ee28ebd8

**Pull request closed without merging**
