### PR TITLE
ENH: zenodo referencing in README.rst + support for ducredit for heudiconv and reproin

### PR DESCRIPTION
**Pull request by yarikoptic**
Individual commits might provide more info.  Here is a result of a sample run with duecredit enabled:

```
DueCredit Report:
- Flexible DICOM converter for organizing brain imaging data / heudiconv (v 0.8.0) [1]
  - ReproIn heudiconv heuristic for turnkey conversion into BIDS / heudiconv.heuristics.reproin (v 0.8) [2]
- I/O library to access to common neuroimaging file formats / nibabel (v 3.0.1) [3]
- Scientific tools library / numpy (v 1.17.4) [4]

3 packages cited
1 module cited
0 functions cited

References
----------

[1] Halchenko, Y. et al., 2020. nipy/heudiconv v0.8.0.
[2] Visconti di Oleggio Castello, M. et al., 2020. ReproNim/reproin 0.6.0.
[3] Brett, M. et al., 2015. Nibabel 2.0.1.
[4] Van Der Walt, S., Colbert, S.C. & Varoquaux, G., 2011. The NumPy array: a structure for efficient numerical computation. Computing in Science & Engineering, 13(2), pp.22–30.
DUECREDIT_ENABLE=1 heudiconv -o /tmp/out -f reproin --files   5.33s user 0.35s system 98% cpu 5.767 total
```

<details>
<summary>With BibTeX output produced by `duecredit summary --format bibtex`:</summary> 

```bibtex
@misc{https://doi.org/10.5281/zenodo.1012598,
  doi = {10.5281/ZENODO.1012598},
  url = {https://zenodo.org/record/1012598},
  author = {Halchenko, Yaroslav and Goncalves, Mathias and Castello, Matteo Visconti Di Oleggio and {Satrajit Ghosh} and Hanke, Michael and Salo, Taylor and {, Dae} and Kent, James and {Pvelasco} and Amlien, Inge and Brett, Matthew and Tilley, Steven and Markiewicz, Chris and Lukas, Darren Christopher and Gorgolewski, Chris and Kim, Sin and {Joerg Stadler} and Kaczmarzyk, Jakub and Lee, John and Lurie, Daniel and Pellman, John and Braun, Henry and Melo, Bruno and Poldrack, Benjamin and Schiffler, Björn and {Michał Szczepanik} and Samuels, Kalle and Carlin, Johan and Feingold, Franklin and Kahn, Ari},
  title = {nipy/heudiconv v0.8.0},
  publisher = {Zenodo},
  year = {2020}
}
@misc{https://doi.org/10.5281/zenodo.1207117,
  doi = {10.5281/ZENODO.1207117},
  url = {https://zenodo.org/record/1207117},
  author = {Visconti di Oleggio Castello, Matteo and Dobson, James E. and Sackett, Terry and Kodiweera, Chandana and Haxby, James V. and Goncalves, Mathias and Ghosh, Satrajit and Halchenko, Yaroslav O.},
  title = {ReproNim/reproin 0.6.0},
  publisher = {Zenodo},
  year = {2020}
}
@misc{https://doi.org/10.5281/zenodo.60847,
  doi = {10.5281/ZENODO.60847},
  url = {https://zenodo.org/record/60847},
  author = {Brett, Matthew and Hanke, Michael and Cipollini, Ben and {Marc-Alexandre Côté} and Markiewicz, Chris and Gerhard, Stephan and Larson, Eric and Lee, Gregory R. and Halchenko, Yaroslav and Kastman, Erik and {Cindeem} and Morency, Félix C. and {Moloney} and Millman, Jarrod and Rokem, Ariel and {Jaeilepp} and Gramfort, Alexandre and Bosch, Jasper J.F. Van Den and {Krish Subramaniam} and Nichols, Nolan and {Embaker} and {Bpinsard} and {Chaselgrove} and Oosterhof, Nikolaas N. and St-Jean, Samuel and {Bago Amirbekian} and Nimmo-Smith, Ian and {Satrajit Ghosh}},
  title = {Nibabel 2.0.1},
  publisher = {Zenodo},
  year = {2015}
}
@article{van2011numpy,
        title={The NumPy array: a structure for efficient numerical computation},
        author={Van Der Walt, Stefan and Colbert, S Chris and Varoquaux, Gael},
        journal={Computing in Science \& Engineering},
        volume={13},
        number={2},
        pages={22--30},
        year={2011},
        publisher={AIP Publishing},
        doi={10.1109/MCSE.2011.37}
        }

```
</details>

### CODE REVIEW

**Comment by yarikoptic** [comment]
if there is no feedback, I would merge tomorrow or so

@mgxd @tsalo @pvelasco et al - please chime in

**Comment by tsalo** [comment]
Would it be worth it to decorate one of the functions in `heudiconv.bids` with the citation for the BIDS paper?

**Comment by pvelasco** [comment]
It looks good to me.

**Comment by yarikoptic** [comment]
> Would it be worth it to decorate one of the functions in `heudiconv.bids` with the citation for the BIDS paper?

that is a good idea!  I would even decorate with the BIDS paper (as documentation or smth) and actual BIDS spec version (we adhere to) as zenodo DOI .  I think we should make it  the latest (1.4.0).  will do later today/tomorrow unless someone beats me to it! ;)

**Comment by yarikoptic** [comment]
forgot about this one, pushed merge conflicts resolution and added BIDS stuff

**Review by tsalo — APPROVED** [review]
All of the changes LGTM.

**Comment by yarikoptic** [comment]
Thank you @tsalo, I will proceed then with merge

**Pull request merged**
