### PR TITLE
Fix certificate issue as indicated in #595

### PR DESCRIPTION
**Pull request by neurorepro**

### CODE REVIEW

**Comment by yarikoptic** [comment]
unfortunately we can't just do that -- Dockerfile is produced using neurodocker, as invoked from https://github.com/nipy/heudiconv/blob/master/utils/gen-docker-image.sh . See if you could set it to install specific version of `conda`. BTW -- in #596 I have not yet got to that error of certificates, but not sure if I reached that point ;)

**Comment by neurorepro** [comment]
@yarikoptic i think i know how to do it with neurodocker, let me try quickly

**Comment by neurorepro** [comment]
@yarikoptic done ! Luckily it was quite easy, setting the version of miniconda caused the conda update command to be skipped as you can see [here](https://github.com/ReproNim/neurodocker/blob/ad2f3a62afa9a8852bbf0ff3f1df1aadb3b74c8d/neurodocker/templates/miniconda.yaml#L44-L46)

**Comment by yarikoptic** [comment]
Cool!
I have just merged my PR which also switched to newer dcm2niix.  If succeeds, I would prefer to stick to newer 3.9 - 3.7 will still be supported for 8 months but that isn't too long and just yesterday my issue known to be present in earlier pythons (iirc 3.7 included) was closed as "we know about the problem and it was addressed in 3.8", so - more anecdotal evidence to go forward with such a change.

With all that in mind -- would you mind updating/replacing this PR with the one which would fix conda installation into 3.9 instead of 3.7? I think it would be useful for robustness of our Dockerfile in the long run.

**Comment by neurorepro** [comment]
Done ! I also tested the Dockerfile building with this PR and it works

**Comment by neurorepro** [comment]
@yarikoptic Question though: shouldn't a dockerfile have fixed versions of dependencies, including for miniconda (i.e. not using latest but a set version as in this PR) ?

**Comment by yarikoptic** [comment]
> Done ! I also tested the Dockerfile building with this PR and it works

cool, thanks!

> @yarikoptic Question though: shouldn't a dockerfile have fixed versions of packages and libraries, including for miniconda (i.e. not using `miniconda-latest` but a specific version such as `miniconda-py39_4.12.0` as in this PR) ?

"may be".  The problem is that complete listing of package versions is tedious  -- those which we list explicitly are just leaves, and they pull in bunch of other packages so versioning only our leaves is ... close to "no point".

In https://github.com/ReproNim/reproin/ I somewhat duplicate the effort done here with package building, but there I build relying on NeuroDebian, not conda, distribution: https://github.com/ReproNim/reproin/blob/master/generate_container.sh , and I use developed by us "nd_freeze" helper which freezes state of the Debian and NeuroDebian distribution to a specific date -- as a result with that single "version" specification I make build reproducible.

may be I should finally meld both approaches here in this repo (there is nothing "reproin" specific in reproin container), ... may be... some time

**Comment by neurorepro** [comment]
@yarikoptic i think all your efforts of freezing packages, + setting packages version via conda, etc. shouldn't leave to many leaves unchecked, so i'd tend to be more optimistic :) or at least it leaves fewer to sweep when debugging irreproducible content...

**Pull request merged**
