### PR TITLE
ENH: reincarnate the paranoid test of a json tuned up with regular expressions

### LINKED ISSUE #104: bring back an assert for correctness of regex-tuned json for the paranoid Yarik
In 12e94ea8533d3b49c2c733a313f6baf507ce42e8 it was commented out.

@satra , was the issue that some floating point number changed its value/json serialization somehow?  do you happen to remember where/how did it happen, since I think it should've not happened (at least never happened to me).

that assert is kinda critical to have in one form or another to guarantee that ugly regex tuning of output didn't backfire

### PR DESCRIPTION
**Pull request by yarikoptic**
Fixes #104

### CODE REVIEW

**Comment by yarikoptic** [comment]
@mgxd do you by any chance remember on which dataset you ran into such numeric difference?  now it should be all legit imho

**Comment by satra** [comment]
@yarikoptic - can you try it one of your prisma scans without `--minmeta` ? we ran into it i believe with the `--minmeta` option on one of our scans.

**Comment by yarikoptic** [comment]
ok, I could try **with** `--minmeta` since I actually didn't use it recently

But note that this one is different from before where I was comparing against original structure, not the one reloaded from the non-perturbed string dump

**Comment by yarikoptic** [comment]
ok, ran on a sample dataset with this change with and without --minmeta, nothing crashed, so it must be solid ;)

once again -- if now assertion fails it would mean that regexes actually modify the data, which they shouldn't so a crash would be warranted.

**Pull request merged**
