### PR TITLE
Drop Python 3.7 support

### PR DESCRIPTION
**Pull request by yarikoptic**
- [x] Might need #721 merged first since resolves problem with deprecation warning on 3.11 which would be relevant here

### CODE REVIEW

**Comment by yarikoptic** [comment]
@jwodder -- do you have quick clue on why we get older setuptools installed

```
2023-12-08T22:32:04.1539412Z   × pip subprocess to install build dependencies did not run successfully.
2023-12-08T22:32:04.1540645Z   │ exit code: 2
2023-12-08T22:32:04.1541435Z   ╰─> [110 lines of output]
2023-12-08T22:32:04.1542543Z       Ignoring numpy: markers 'python_version == "3.7"' don't match your environment
2023-12-08T22:32:04.1544530Z       Ignoring numpy: markers 'python_version >= "3.8" and python_version < "3.11"' don't match your environment
2023-12-08T22:32:04.1545934Z       Collecting setuptools==60.5
2023-12-08T22:32:04.1546922Z         Downloading setuptools-60.5.0-py3-none-any.whl (958 kB)
2023-12-08T22:32:04.1548651Z            ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 959.0/959.0 kB 26.6 MB/s eta 0:00:00
```
so that we get
```
        File "/tmp/pip-build-env-pb4b294m/overlay/lib/python3.12/site-packages/setuptools/__init__.py", line 10, in <module>
          import distutils.core
      ModuleNotFoundError: No module named 'distutils'
```
on py 3.12
?

**Comment by jwodder** [comment]
@yarikoptic This is the fault of pylibjpeg-libjpeg.  [Its build requirements](https://github.com/pydicom/pylibjpeg-libjpeg/blob/0378f4d11cd7f68af1a49d95e30351a3840eba01/pyproject.toml) pin setuptools for some reason, but the actual build failure is due to the fact that these requirements specify exactly numpy 1.23.2 on Python 3.11 and above, and that version (which was released over a year ago) requires distutils to install.

**Comment by yarikoptic** [comment]
Thank you @jwodder for the analysis!!! my humble attempt https://github.com/pydicom/pylibjpeg-libjpeg/pull/48

**Comment by yarikoptic** [comment]
meanwhile I will just drop attempt at 3.12 here, so we will just end up dropping 3.7

**Pull request merged**
