### PR TITLE
try a simple fix for wrongly ordered files in tar file

### PR DESCRIPTION
**Pull request by bpinsard**
solves #519

### CODE REVIEW

**Comment by yarikoptic** [comment]
But isn't the underlying issue that we (or is it a heuristic?) have some order effect?

**Comment by yarikoptic** [comment]
File names could be 1, 2, ..., 10 and string sorting would screw it up

**Comment by bpinsard** [comment]
You're right, our files are alphanumerically sorted by acquisition/content-creation order because it uses Siemens UID, and that might not be the general case.
However, I think it is sorted as well when not pulled from a tar filed (eg obtained from a directory).
https://github.com/nipy/heudiconv/blob/80a65385ef867124611d037fceac27d27e30f480/heudiconv/parser.py#L163-L164

In most cases the order of the file won't matter to the indexing nor to dcm2niix.

But for that particular case described in #519 :  complex data (at least 2 dicoms with M and P ImageType) in a single series will give a varying ImageType to the seqinfo depending on the sorting, as the parse will choose the first one as the example dicom.

**Comment by yarikoptic** [comment]
your argument that we sort in non-tar handling convinces me. Let's proceed with this, and see if any fallout happens ;) Thank you @bpinsard !

**Pull request merged**
