### PR TITLE
BF (reproin, PY3): cast seqinfos into a list so entries could be modified if necessary

### PR DESCRIPTION
**Pull request by yarikoptic**
this fix is specific to python 3.x , see comment in the change

### CODE REVIEW

**Comment by yarikoptic** [comment]
uff, tests for python3 fail due to some breakage of API in traits:
https://travis-ci.org/nipy/heudiconv/jobs/650584044?utm_medium=notification&utm_source=github_status 

```
...
  File "/home/travis/build/nipy/heudiconv/venv/lib/python3.5/site-packages/nipype/__init__.py", line 61, in <module>
    from .pipeline import Node, MapNode, JoinNode, Workflow
...
  File "/home/travis/build/nipy/heudiconv/venv/lib/python3.5/site-packages/nipype/interfaces/base/core.py", line 34, in <module>
    from .traits_extension import traits, isdefined
  File "/home/travis/build/nipy/heudiconv/venv/lib/python3.5/site-packages/nipype/interfaces/base/traits_extension.py", line 27, in <module>
    from traits.trait_handlers import TraitType, NoDefaultSpecified
ImportError: cannot import name 'TraitType'
The command "coverage run `which py.test` -s -v heudiconv" exited with 2.
```
@mgxd @satra - anything obvious/known?

**Comment by satra** [comment]
@yarikoptic - there was a nipype release 2 days back (1.4.2). can you try that one?

**Comment by yarikoptic** [comment]
yeap, newer nipype was installed and seems ok. now the issue is datalad. #415 is to fix that first

**Comment by yarikoptic** [comment]
d'oh - I thought we had it merged so I removed it... will resurrect, make sure that tests pass, and then merge

**Pull request closed without merging**
